# Music
XGM lvlclr "vgm/victory.vgm"
XGM gameover "vgm/gameover.vgm"
XGM rboss "vgm/boss.vgm"
XGM fboss "vgm/boss2.vgm"
XGM ending "vgm/end.vgm"
XGM testtrck "vgm/testvgm.vgm"
XGM titlevgm "vgm/title.vgm"
#-Stage-Themes--------------------
XGM elevator "vgm/elevator.vgm"
XGM stg1 "vgm/city.vgm"
XGM stg2 "vgm/city2.vgm"
XGM stg3 "vgm/bar.vgm"
XGM stg4 "vgm/alley.vgm"
XGM stg5 "vgm/bridge.vgm"
XGM stg6 "vgm/station.vgm"
XGM stg7 "vgm/train.vgm"
XGM stg8 "vgm/final.vgm"